config/routes.rb
Rails.application.routes.draw do
  resources :glucose_checks

  get 'welcome/index'

  devise_for :users

  resources :index

  get 'welcome/index'
  root 'welcome#index'

end

app/models/glucose_check.rb
class GlucoseCheck < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/glucose_checks_controller.rb
class GlucoseChecksController < ApplicationController
  before_action :set_glucose_check, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @glucose_checks = GlucoseCheck.all
    respond_with(@glucose_checks)
  end

  def show
    respond_with(@glucose_check)
  end

  def new
    @glucose_check = GlucoseCheck.new
    respond_with(@glucose_check)
  end

  def edit
  end

  def create
    @glucose_check = GlucoseCheck.new(glucose_check_params)
    @glucose_check.save
    respond_with(@glucose_check)
  end

  def update
    @glucose_check.update(glucose_check_params)
    respond_with(@glucose_check)
  end

  def destroy
    @glucose_check.destroy
    respond_with(@glucose_check)
  end

  private
    def set_glucose_check
      @glucose_check = GlucoseCheck.find(params[:id])
    end

    def glucose_check_params
      params.require(:glucose_check).permit(:glucose)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!, only: [:welcome]
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/glucose_checks_helper.rb
module GlucoseChecksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/glucose_checks/_form.html.erb
<%= form_for(@glucose_check) do |f| %>
  <% if @glucose_check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@glucose_check.errors.count, "error") %> prohibited this glucose_check from being saved:</h2>

      <ul>
      <% @glucose_check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :glucose %><br>
    <div class="input-group input-group-lg">
    <%= f.text_field :glucose, placeholder:'Glucose Reading', class: "form-control" %>
  </div>
  <div class=".btn-block">
    <%= f.submit "Submit", :class => "glucoseSubmit login btn btn-primary btn-lg"%>
  </div>
<% end %>

app/views/glucose_checks/edit.html.erb
<div class="wrapper">
  <div class="block">
  <div class="form">
  <div class="table">

<h1>Editing Sugar Checks</h1>

<%= render 'form' %>

<%= link_to 'Show', @glucose_check %> |
<%= link_to 'Back', glucose_checks_path %>
</div>
</div>
</div>
</div>

app/views/glucose_checks/index.html.erb
<div class="wrapper">
  <div class="block">
  <div class="form">
  <div class="table">

<h1>List your measured Sugar level </h1>


<table>
  <thead>
    <tr>
      <th>Glucose</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @glucose_checks.each do |glucose_check| %>
      <tr>
        <td><%= glucose_check.glucose %></td>

        
          <td><%= link_to 'Show', glucose_check, :class =>'spacer' %></td>
        

        
          <td><%= link_to 'Edit', edit_glucose_check_path(glucose_check),:class =>'spacer' %></td>
       

        
          <td><%= link_to 'Destroy', glucose_check, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'spacer' %></td>
       

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Glucose check', new_glucose_check_path %>
</div>
</div>
</div>
</div>    

app/views/glucose_checks/new.html.erb
<div class="wrapper">
  <div class="block">
  <div class="form">
  <div class="table">

<h1>Whats your Sugar level</h1>


<%= render 'form' %>
<div class="back">
<%= link_to 'Back', glucose_checks_path , :class => 'backBtn'%>
</div>
</div>
</div>
</div>
</div>

app/views/glucose_checks/show.html.erb
<div class="wrapper">
  <div class="block">
  <div class="form">
  <div class="table">
<p id="notice"><%= notice %></p>

<p>
  <strong>Glucose:</strong>
  <%= @glucose_check.glucose %>
</p>

<%= link_to 'Edit', edit_glucose_check_path(@glucose_check) %> |
<%= link_to 'Back', glucose_checks_path %>

</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ALRFewdFinalProject</title>

  
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Antic' rel='stylesheet' type='text/css'>
  <link href="https://fontastic.s3.amazonaws.com/XPnNwEHKrqA6C6KTDq55RC/icons.css" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ALR Final Project</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/glucose_checks">Dashboard</a></li>
      </ul>

      <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", glucose_checks_path, :class => 'navbar-link'  %>
<% end %>

    </div>
  </div>
</nav>

        <%= yield %>

<footer>
  <div class="container">
      <div class="social">       
          <a class="icon-social-facebook"  href="#"></a>
          <a class="icon-social-twitter"   href="#"></a>
          <a class="icon-social-instagram" href="#"></a> 
      </div>

    <p>Angel Reyes FEWD Final Project 2014</p>
  </div>
</footer>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/welcome/index.html.erb
<div class="mainBody">
	<div class="heroWrap"> 
		<div class="hero">
			<div class="emptyBox">	
				<h2>Continuous Glucose Monitoring on the go!</h2>
				<a class="signUp" href="users/sign_up">Sign Up</a>
			</div>

			<div class="scrollDown">
				<p>Scroll Down</p>
				<a class="icon-chevron-down" href="/"></a>
			</div>
		</div>
	</div>


	<div class="mainContent">
		
		<h3>How it works</h3>
		
		<div class="row">
			<div class="rowOne">
				<div class="col-sm-3">
					<img id="imgOne"src="https://dt8kf6553cww8.cloudfront.net/static/images/index/1-vflbLvAPq.png" alt="">
					<article id="parOne">
						<h2>Information where you are</h2>
						<p>Meter your Glucose levels on the go and understand it wherever you are. </p>
		 			</article>	 								
				</div>
			</div>			
		</div>
		

		<div class="row">
			<div class="rowTwo">
				<div class="col-sm-3">

					<img id="imgTwo"src="https://dt8kf6553cww8.cloudfront.net/static/images/index/2-vflawKxYX.png" alt="">
					<article id="parTwo">
						<h2>Share with your loved ones</h2>
		    			<p>Share your Sugar levels with your love ones and take action controling your sugar intakes.</p>
		  			</article>
		  		</div>
	  		</div>
	  	</div>	
		
		<div class="row">
			<div class="rowThree">
				<div class="col-sm-3">
					<img id="imgThree"src="https://dt8kf6553cww8.cloudfront.net/static/images/business/home/file-share-transfer-devices-vfl7Qrx9H.png" alt="">
		 			 <article id="parOne">
		 			 	<h2>Advance Analizing Tools</h2>
		    			<p>Download the data from your CGM and analize it with our advance tools</p>
		 			 </article>
		 		</div>
	 		</div>
	 	</div>

	 	<div class="row">
			<div class="rowFour">
				<div class="col-sm-3">

					<img id="imgFour"src="https://dt8kf6553cww8.cloudfront.net/static/images/index/3-vflwYDamk.png" alt="">
		 			 <article id="parTwo">
		 			 	<h2>Safe & easy to use</h2>
		   				 <p>With a strong account protection you can have peace of mind storing your CGM files in your account.</p>
		 			 </article>
				</div>
			</div>
		</div>	
	</div>
	
</div>